# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: handsomehow
description: handsomehow,cpp
keywords: handsomehow,cpp
url: http://www.handsomehow.com
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: handsomehow
    email: handsomehowyxh@gmail.com
    imageLink: /images/header.png
    simpleIntro: Nothing is left because the auther is too lazy
    detailIntro:
      <p>本科在读....</p>
      <p>智障儿童....</p>
      <p></p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/
  - class: icon-facebook
    url: http://facebook.com/
  - class: icon-github-alt
    url: https://github.com/handsomehow/
  - class: icon-twitter
    url: https://twitter.com/handsomehow

#Links
customLinks:
  - item:
    - text: old blog
      url: http://blog.csdn.net/handsomehow
    message: old blog    
  - item:
    - text: swjtu Online Judge
      url: http://swjtuoj.cn
    - text: twh233
      url: http://blog.csdn.net/qq_36553623
    - text: Desgard_gua
      url: http://www.desgard.com/
    - text: HackSwjtu
      url: http://www.hackswjtu.com/
    message: Friends  
    

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-58146229-1

